# Generated by Django 2.2 on 2020-06-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='jic', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_by', models.CharField(default='jic', max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(help_text='分数值')),
                ('user', models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.PROTECT, related_name='fractions', to='user.User')),
            ],
            options={
                'verbose_name': '分数',
                'verbose_name_plural': '分数',
                'db_table': 'fraction',
            },
        ),
    ]
